apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: basic-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') 
                    \ {\n stage 'Build the nodetest app'\n openshiftBuild(namespace: 'pipelinesimple', buildConfig: 'nodetest', showBuildLogs: 'true')\n
                    \ stage 'Deploy the nodetest app'\n openshiftDeploy(namespace: 'pipelinesimple', deploymentConfig: 'nodetest')\n 
                    \   stage 'Scale the nodetest app to 3 pods'\n openshiftScale(namespace: 'pipelinesimple', deploymentConfig: 'nodetest',replicaCount: '3', verifyReplicaCount: 'true')\n
                    \ }\n"
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
